services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest

  producer:
    build: ./producer
    depends_on:
      - rabbitmq
    environment:
      - RABBITMQ_HOST=rabbitmq

  consumer_a:
    build: ./consumer_1
    depends_on:
      - rabbitmq
    environment:
      - RABBITMQ_HOST=rabbitmq

  consumer_b:
    build: ./consumer_2
    depends_on:
      - rabbitmq
    environment:
      - RABBITMQ_HOST=rabbitmq
